var array = ["SSC", "HSC", "BCS", "BS", "BCOM", "MS", "M.PHILL", "PhD"];
document.write("<b>Qualification:</b>");
document.write("<br>" + array[0] + "<br>");
document.write("<br>" + array[1] + "<br>");
document.write("<br>" + array[2] + "<br>");
document.write("<br>" + array[3] + "<br>");
document.write("<br>" + array[4] + "<br>");
document.write("<br>" + array[5] + "<br>");
document.write("<br>" + array[6] + "<br>");
document.write("<br>" + array[7] + "<br>");
